### ISSUE TITLE
Caught Exception from Modular Controller: Missing registryname

### ISSUE THREAD

**Issue by Hoenn-Otaku** [ProjectHDS/ModularController#6]
During Init, Modular Controller crashes the game. This occurs on the 1.1.4 and 1.1.5 versions. I have Modular Machinery 1.10.0, Modular Magic 1.4.0, and Modular Diversity 1.10. 

The error log starts off like this:
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Modular Controller (modularcontroller)
Caused by: com.google.gson.JsonSyntaxException: Missing registryname, expected to find a string
    at net.minecraft.util.JsonUtils.getString(SourceFile:107)
    at youyihj.modularcontroller.util.MachineJsonPreReader.deserialize(MachineJsonPreReader.java:18)
    at youyihj.modularcontroller.util.MachineJsonPreReader.deserialize(MachineJsonPreReader.java:11)`

[crash-2022-02-27_15.37.32-client.txt](https://github.com/ProjectHDS/ModularController/files/8149416/crash-2022-02-27_15.37.32-client.txt)

Any ideas?

**Comment by friendlyhj** [comment]
Your machine json is invalid.
